add_rules("mode.debug", "mode.release")
add_requires("jsoncpp", "libcurl", "readline")
target("gf")
    set_languages("c++17")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("jsoncpp", "libcurl", "readline")
